apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_application-deployment
  labels:
    app: my_application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my_application
  template:
    metadata:
      labels:
        app: my_application
    spec:
      containers:
        - name: my_application-container
          image: my_docker_username/my_app:latest
          ports:
            - containerPort: 3000
